### ISSUE TITLE
Issue with unique ID

### ISSUE THREAD

**Issue by zeronounours** [zeronounours/HA-custom-component-energy-meter#1]
In the way it is implemented, energy utility meters & cost utility meters sensors will have the same unique ID if defined within the configuration.

**Configuration**
```yaml
energy_meter:
  daily_energy:
    unique_id: daily_energy_meter
    source: sensor.energy
    name: Daily Energy
    cycle: daily
    price_entity: sensor.energy_price
    tariffs:
      - peak
      - offpeak
```

**Logs**
```
2023-05-21 12:57:24.679 ERROR (MainThread) [homeassistant.components.sensor] Platform utility_meter does not generate unique IDs. ID daily_energy_meter_peak is already used by sensor.daily_energy_peak - ignoring sensor.daily_energy_cost_peak
```
