### ISSUE TITLE
Decimal setting and unique_id

### ISSUE THREAD

**Issue by kongjudas** [zeronounours/HA-custom-component-energy-meter#35]
I get a lot of decimals from the cost entities and can't truncate it because the entities doesn't have a unique ID. I'm sure the many decimals comes from the source entities, so it's not an issue with the energy meter.

A setting to adjust decimals and unique_id function would be nice.

**Comment by Roving-Ronin** [comment]
@kongjudas

Where aren't you getting a unique_id as I appear to get them with the energy meter?

Also the decimal places can be manually set, if you can access the entity settings (with a unique ID).
However given these cost sensors are outputting a $ figure, that should be in $0.00 (2 decimal places) format, it would be an idea for the integration code to be updated to specify the created sensors default to 2 decimal places.

When normally defining a sensor etc with a 'state: ' formula, this would be achived using the 
```
round(2) 
```
function, normally I'd try submit a PIR for the code, however with no experience of the coding for the underlying integration I'm not sure where / how this should be updated in the code.
@zeronounours is this something you would consider adding a default 2 decimal places for the $ / energy meter sensors created?

**Comment by zeronounours** [comment]
A unique ID are normally generated at the utility_meter level and the EnergyCostSensor. What sensor is missing one? Or maybe the id clash with another one?

@Roving-Ronin, this integration do not reimplement the builtin utility_meter et EnergyCostSensor, it mainly uses them all. Rounding should normally be done at the UI level (lovelace). The issue with rounding at the sensor level is to create a difference with reality over time. The EnergyCostSensor is mainly doing a sum of energy over-time. If you round the value each cycle, you will loose info. For instance, if you get 1.234 then 1.234 then 2.234, your consumption will be 1.23 then 2.46 eth 4.69 intead of 1.234, 2.468 and 4.50.

**Comment by alfwro13** [comment]
I seem to have the same  problem. The Cost entities are generating values with 16 decimal places and without the unique ID there is no way using the UI to change that:
![image](https://github.com/zeronounours/HA-custom-component-energy-meter/assets/10945277/633169c6-5175-4145-9d6c-02d6e5144873)

**Comment by zeronounours** [comment]
Could you provide associated configuration please? I can't reproduce it in the lab

**Comment by Roving-Ronin** [comment]
Re the unique_id I notice that in other issue thread's the example yaml is like below, that I assume is what people are using?
```
energy_meter:
  daily_energy:
    source: sensor.energy
    name: Daily Energy
    cycle: daily
    price_entity: sensor.current_energy_price
    tariffs:
      - peak
      - offpeak
```

Using this format (below), personally I note that I get unique_id's on the lot:
```
energy_meter:
  daily_energy:
    name: Daily Energy
    unique_id: daily_energy
    source: sensor.energy
    cycle: daily
    price_entity: sensor.current_energy_price
    tariffs:
      - peak
      - offpeak
```
