### ISSUE TITLE
Calibrate energy Meter

### ISSUE THREAD

**Issue by Bluhme1** [zeronounours/HA-custom-component-energy-meter#42]
Are there any possibilities to reset or calibrate the Energy Meter sensors in the same way as the original Utility Meter

Thanks for a great job

/Lars (Denmark)

**Comment by home409ca** [comment]
it works....

```
service: utility_meter.calibrate
data:
  value: "0"
target:
  entity_id: sensor.energia_import_netto_rocznie_pse_cost
```
![image](https://github.com/zeronounours/HA-custom-component-energy-meter/assets/114701129/13ec4135-4a7c-4d89-9238-6285f79ce75e)
