### ISSUE TITLE
Add option for daily standing charge

### ISSUE THREAD

**Issue by alfwro13** [zeronounours/HA-custom-component-energy-meter#50]
It would be great if there was an option to add (either static or from a sensor) daily standing charge to the cost. 
Thanks

**Comment by zeronounours** [comment]
This integration rely on the builtin Energy sensor and utility meter. I won't add features that is not already supplied by them.
As of today, it is not supported by the Energy sensors, even if a feature request is opened for that: https://community.home-assistant.io/t/energy-add-fixed-daily-cost/330609/62

If/when implemented, I might add the same thing to this integration. Feel free to comment / reopen the issue if this is finally implemented.

If you want to add a standing charge, you'd better use a template entity for that:

```yaml
energy_meter:
  daily_energy:
    source: sensor.energy
    name: Daily Energy
    cycle: daily
    price_entity: sensor.current_energy_price
    tariffs:
      - peak
      - offpeak

template:
  - sensor:
      - name: "Daily Electricity Price"
        unit_of_measurement: "USD"
        state: >
          {% set peak = states('sensor.daily_energy_cost_peak') | float %}
          {% set offpeak = states('sensor.daily_energy_cost_offpeak') | float %}
          {% set standing_charge = states('sensor.daily_standing_charge') | float %}

          {{ peak + offpeak + standing_charge }}
```
