### ISSUE TITLE
Utility Meter: Reset - Doesn't work with Energy Meter

### ISSUE THREAD

**Issue by Roving-Ronin** [zeronounours/HA-custom-component-energy-meter#52]
Hi @zeronounours / Gauthier,

Could you please advise upon this issue. I've just reached by Gas 'end of quarter' meter reading date and usually when using the utility_meter option an automation would kick in and call the 'Utility Meter: Reset' service that would then target the sensor.gas_consumed_quarterly_mj entity to reset it back to 0 (mj) for the quarter.

Just checking now and found whilst the automation has triggered, the entity hasn't reset to zero.  Editing the automation and checking the target, as it also needs the sensor.gas_consumed_quarterly_mj_cost entity added to the automation to reset the quarterly cost to zero and discovered that the 'Utility Meter: Reset' appears to ONLY allow selecting a 'utility meter' sensor, with the 'energy_meter' sensors not be an option to see and select.

I've also tried manually adding an automation, in case it was just the GUI editor not allowing us to see/select energy_meter sensors:

```
alias: Gas - Quarterly Meter Reset
description: Reset the gas readings totals when meter reading taken
trigger:
  - platform: calendar
    event: start
    offset: "8:0:0"
    entity_id: calendar.gas_meter_reset
condition: []
action:
  - service: utility_meter.reset
    data: {}
    target:
      entity_id:
        - sensor.gas_consumed_quarterly_mj
        - sensor.gas_consumed_quarterly_mj_cost
mode: single
```

and confirm even trying this manually is not working. Could you please advise if there is some work around or way you reset the energy_meter and associated cost sensors?

Out of interest, has there been any update on getting the functionality of the energy meter added into Home Assistant (i.e. adding to or replacing utility_meter), as I would think if this was done, then the 'Utility Meter: Reset' service (or a new 'Energy Meter: Reset' service) would be integral to HA.

__________________________________________________________________
UPDATE: 

Still probably worth investigating getting the 'Utility Meter: Reset' updated to also work with Energy Meter (or a 'Energy Meter: Reset' added to HA), but to answer my own question re a temporary work around, I found that the utility_meter.calibrate service recognises the Energy Meter sensors and can be used to set them to zero.

Here is what I setup an an automation, that checks a calendar I've setup called 'Gas Meter Reset' and in which I define an entry on the approximate (buggers here can go anywhere from mid 80 to low 90 days in a quarter between readings) day and time when the meter reading guy checks the meter.  Based upon that as the trigger, it then calls the utility_meter.calibrate service and sets it to zero (or the number defined in the automation).

Note: Users who have a monthly or quarterly meter reading that falls with 28 days of the start of the month or quarter (i.e. within 28 days of 1 Jan / 1 Apr / 1 July / 1 Oct) will not have this problem, as you can simply use the following, if you meter reading is half way through the quarter, then you'll have this issue also.

```
cycle: monthly
offset: 28
```
or 
```
cycle: quarterly
offset: 28
```

The 'work around' automation:

```
alias: Gas - Energy Meter Reset
description: Use the utility_meter.calibrate service to set the gas MJ and Cost to ZERO.
trigger:
  - platform: calendar
    event: start
    offset: "8:0:0"
    entity_id: calendar.gas_meter_reset
condition: []
action:
  - service: utility_meter.calibrate
    data:
      value: "0"
    target:
      entity_id:
        - sensor.gas_consumed_quarterly_mj
        - sensor.gas_consumed_quarterly_mj_cost
mode: single

```

Thanks !
