### ISSUE TITLE
Add possibility to only create a cost sensor onto an already existing LTS

### ISSUE THREAD

**Issue by rrozema** [zeronounours/HA-custom-component-energy-meter#54]
**Is your feature request related to a problem? Please describe.** 
I find that when using the energy-meter component I often already have a LTS entity -not created through a utility-meter- for which I want to add a cost or compensation sensor. As the energy-meter always creates both the cost sensor and the utility-meter I often find myself getting duplicate LTS sensors for the exact same value.

**Describe the solution you'd like** 
I'd like a way to define an energy-meter that only adds the costs/compensation sensor to an existing LTS entity.

**Describe alternatives you've considered** 
I can't think of any alternative to create only a cost sensor without adding a duplicate LTS entity.

**Additional context** 
N/A

**Comment by zeronounours** [comment]
Hello @rrozema
To be sure to understand, let's take an example
```yaml
energy_meter:
  daily_energy:
    source: sensor.energy
    name: Daily Energy
    cycle: daily
    price_entity: sensor.current_energy_price
    tariffs:
      - peak
      - offpeak
```
This config will create entities the following entities
- Utility meter for the energy: 2 sensors peak/offpeak + select tariff
- the energy costs sensor
- Utility meter for the energy costs: 2 sensors peak/offpeak + select tariff

Your issue is the existence of the energy costs sensor and you'd like only the utility meter for it ?
