### ISSUE TITLE
entity_id of the cost sensor is to complicated

### ISSUE THREAD

**Issue by rrozema** [zeronounours/HA-custom-component-energy-meter#57]
**Is your feature request related to a problem? Please describe.** 
The entity_id for the cost sensor seems in v1.1.0 composed from the id of the source entity and the id of price entity. This results in potentially very long and not very clear entity ids. Also, this results in the id of the cost sensor to change if either the source sensor or the price sensor is changed.

**Describe the solution you'd like** 
I suggest to compose the entity id of the cost sensor as the name of the energy_meter post-fixed with "_cost". And the name of the utility meter as the name of the energy meter itself. For example if I add this definition:
```yaml
energy_meter:
  electricity_total_used:
    source: sensor.energy_used
    name: "Total electricity used"
    unique_id: electricity_total_used
    price_entity: sensor.electricity_meter_energy_consumption_price
```
I would get:
- a utility_meter entity with entity_id: sensor.electricity_total_used
- a cost sensor with entity_id: sensor.electricity_total_used_cost

This matches how the energy dashboard names its utility meter and cost sensor pairs, plus it makes sure that both meter and cost sensor can be easily identified as the result of this energy meter. And on top of that the generated sensor names are predictable and reproduceable, as they are now not dependent on any of the properties of the energy meter other than the name used to define the energy meter.

**Describe alternatives you've considered** 
None

**Additional context** 
The change in the sensor naming with the upgrade to v1.1.0 completely broke my existing configuration as the old sensors had become unavailable and new ones with unexpected ids were added instead: I had to do quite some trickery to get my historic data back and my dashboards working again.
Please also consider adding a cost_name: property too, which would define the name for the cost sensor like the name: property does for the utility sensor.

**Comment by Roving-Ronin** [comment]
@rrozema 
I think that the entity ID for the cost sensor has been based upon the "source entity _+_ id of price entity" formula from the initial release of Energy Meter.  Here's my Energy Meter(s) from v1.0.1 demonstrating this.

![image](https://github.com/zeronounours/HA-custom-component-energy-meter/assets/108674933/66d75462-cd3c-4362-999d-5107d4159844)

Personally they are a bit 'long' but they do assist with actually ID'ing them and given there's no need to touch them, I just hide them anyhow. If changing to a _cost suffix it needs to be a 'one time' and final change if this will stuff up everyone's existing sensors / automations etc.
I would concur however with the  "cost_name:"  suggestion, assuming it could be taken from the source sensors name (i.e. name: "Total electricity used" from the example above) and just add " - Cost" to it as a suffix.

**Comment by rrozema** [comment]
The entity_id's as generated by energy_meter are not only long, worse is that these compound names do not follow a proper naming scheme. The most problematic point however -I think- is that they depend on attributes of the energy_meter. i.e. if one of those attributes changes, what do you do? If you change the name of all entity_id's you'll break any dashboards and scripts using the entity, but if you leave them unchanged, they no longer match the attributes and thus ID'ing the sensor with the energy_meter that created it will no longer work.

I think that you not having any issues during the upgrade is because you left the entity_id's unchanged from how they were generated. Any user that changes the entity_id's will get it's configuration broken already from this upgrade from 1.0.1. to 1.1.0. I think the sensors created should all get unique_id's assigned, next to their entity_id. I'll explain below what I mean by these.

I actually do change my entity id's a lot because I want all of my entities to follow a proper naming scheme. This is also why each entity has 3 different 'unique' attributes, each has it's own purpose:
The name property is used for displaying purposes, i.e. it's what is shown to an end user on f.e. a dashboard.
The entity_id is how the 'admin' user identifies any particular entity for putting it on dashboards, in lists, etc. and 
The unique_id is how the database keeps track of each unique entity's properties and history.

Being the 'admin' user in my home I like my entities all to have entity_id's that are 'logical', not based on and chosen by the integration. I try to keep all of my entities' ids named to include the area, device name, plus the specific property they hold. For example, sensor.richard_filamentdroger_electric_consumption_kwh is the energy usage for the filament dryer I have in my room.  sensor.richard_filamentdroger is the switch for that filament dryer. sensor.richard_filamentdroger_plug_electric_consumption_kwh is the usage of the wall-plug device I use to measure that filament dryer's usage. sensor.woonkamer_temphum_temperature is the temperature as measured by the tempature & humidity device in our living room. etc. If they are not generated as such I rename them following this schema: No matter the integration the entities are created by, I can always find the proper sensor and I can always predict what the name of any sensor I'm looking for will be without having to look it up. To support this I also name all my devices like <area>: <devicename>, (f.e. "Richard: Filamentdroger", "Richard: Filamentdroger: Plug" and "Woonkamer: TempHum") which automatically results in most integrations giving the device's entities names pretty much following my schema.

This is what I think it should look like to fix all of the above mentioned issues and give the admin user the freedom to rename any entity_id and names as they see fit without risking to lose all of their historic data at a future upgrade of the energy_meter integration or when the definition of an energy meter needs to be changed.
```yaml
energy_meter:
  electricity_total_used:
    source: sensor.energy_used
    name: "Total electricity used"
    cost_name: "Cost for electricity used"
    unique_id: electricity_total_used
    price_entity: sensor.electricity_meter_energy_consumption_price
```
generates a utility meter with:
```
entity_id: sensor.electricity_total_used
unique_id: sensor.electricity_total_used
name: Total electricity used
```
plus a cost meter with:
```
entity_id: sensor.electricity_total_used_cost
unique_id: sensor.electricity_total_used_cost
name: Cost for electricity used
```

**Comment by zeronounours** [comment]
I'm against adding a `cost_name` configuration.

To prevent duplicates energy cost sensors, only one is created per tuple (`source`, `price_entity`). This way, if you track through energy_meter both daily and monthly consumption, you won't end up with two similar entities.

If both energy_meter have a different `cost_name`, the result `entity_id` will be unpredictable. Worst, it may change from one restart to another (home assistant is asynchronous and you can't know which entity creation will be scheduled first). It would be way more confusing for users than a long `entity_id`.

This is precisely why Home Assistant has introduced `unique_id`. It is the only identifier which allows tracking a sensor on `entity_id` changes: see [Home Assistant FAQ on that](https://www.home-assistant.io/faq/unique_id/). When you don't have a `unique_id`, you cannot change the `entity_id`, otherwise it would be similar to deleting the old one and creating a new one.

The use of `unique_id` is a bit awkward at first, but it is an important concept in Home Assistant. It is the reason why no Home Assistant allows to define the `entity_id`: you may only partly control its initial value. And because `unique_id` is defined on the energy cost sensor, you can safely change its `entity_id` to something shorter.

Energy cost sensors define a `unique_id` based on the source sensor and price entity. If both source sensor and price entity have a `unique_id`, you can safely change the `entity_id` of either one and it won't break the cost sensor and it won't change its `entity_id`. If you change a source or price entity with no `unique_id`, it would be a new sensor and energy cost sensor should be recreated too. It is an expected behavior.

Take the following example:
```yaml
input_number:
  energy_price:
    name: Energy price input
    initial: 2
    min: 0
    max: 100
    step: 0.5
  power:
    name: Power input
    initial: 1000
    min: 0
    max: 10000
    step: 100

template:
  - trigger:
      - platform: time_pattern
        hours: "*"
        minutes: "*"
        seconds: "*"
    sensor:
      - name: Energy price
        state: "{{ states('input_number.energy_price') }}"
        unique_id: energy_price
        unit_of_measurement: USD/kWh
        device_class: monetary
        attributes: # to force update every seconds for integration
          attribute: "{{ now().second }}"
      - name: Power
        state: "{{ states('input_number.power') }}"
        unit_of_measurement: W
        device_class: power
        attributes: # to force update every seconds for integration
          attribute: "{{ now().second }}"

sensor:
  - platform: integration
    source: sensor.power
    unique_id: energy_sensor
    name: energy
    unit_prefix: k

energy_meter:
  daily_energy:
    unique_id: daily_energy_meter
    source: sensor.energy
    name: Daily Energy
    cycle: daily
    price_entity: sensor.energy_price
    tariffs:
      - peak
      - offpeak
```
Here, both `sensor.energy_price` and `sensor.energy` have a `unique_id`. You can safely change the `sensor.energy_price` `entity_id` to something else, and change it within the energy_meter config. The result cost sensor won't change and will still have the same name.


As a side note, I would highly recommend you to define a `unique_id` for every entity you create.
