### ISSUE TITLE
 'Unknown' value

### ISSUE THREAD

**Issue by AFPass** [zeronounours/HA-custom-component-energy-meter#76]
Hello,

I have some entries for which no value is displayed for Cost. The message 'Unknown' appears.

This one doesn't work
```
template:
  - sensor:  
    - name: "Solaranlage - Überproduktion - Gesamt in kWh"
        unique_id: 5fa51a99-6751-4487-bbfd-3fd399fbf7de
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.smart_meter_negative_active_energy_in_tariff_t1') | float / 1000 }}"
        device_class: energy
        state_class: total_increasing
```
```
solaranlage_uberproduktion_taeglich_energy:
  source: sensor.solaranlage_uberproduktion_gesamt_in_kwh
  name: Solaranlage - Überproduktion - täglich
  unique_id: 442630c6-835d-48b6-a451-a906f1aef388
  cycle: daily
  price_entity: input_number.aktueller_strompreis_verbrauch
```

This one works:
```
template:
  - sensor:
      - name: "Solaranlage - Produktion - Gesamt in kWh"
        unique_id: fdd4a389-23eb-4fd0-bef1-493532dda537
        unit_of_measurement: "kWh"
        state: "{{ (states('sensor.hoymiles_hms_wifi_41439233_pv_1_energy_total') | float + states('sensor.hoymiles_hms_wifi_41439233_pv_2_energy_total') | float)  / 1000 }}"
        device_class: energy
        state_class: total_increasing
```
```
solaranlage_produktion_taeglich_energy:
  source: sensor.solaranlage_produktion_gesamt_in_kwh
  name: Solaranlage - Produktion - täglich
  unique_id: 44247cd3-ebf9-4b8b-b219-d47c63e9ba89
  cycle: daily
  price_entity: input_number.aktueller_strompreis_verbrauch
```
Version: v1.1.0
